# ============================================================
# Tmux Configuration
# ============================================================

# ------------------------------------------------------------
# Prefix
# ------------------------------------------------------------

unbind C-b
set -g prefix C-a
bind C-a send-prefix


# ------------------------------------------------------------
# General
# ------------------------------------------------------------

set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"
set -g allow-passthrough on

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 10000
set -g mouse on
set -sg escape-time 10
set -g focus-events on
set -g extended-keys on


# ------------------------------------------------------------
# Plugins
# ------------------------------------------------------------

source-file ~/.config/tmux/config/plugins.conf


# ------------------------------------------------------------
# Keybindings
# ------------------------------------------------------------

source-file ~/.config/tmux/config/keybindings.conf


# ------------------------------------------------------------
# Theme / Styling
# ------------------------------------------------------------

source-file ~/.config/tmux/config/theme/styling.conf
