# Kanagawa — minimal
# https://github.com/rebelot/kanagawa.nvim

set -g status-position bottom
set -g status-interval 5
set -g status-justify left
set -g status-style "bg=default,fg=#727169"

set -g status-left-length 40
set -g status-left "#[bg=#FFA066,fg=#1F1F28,bold] #S #[bg=default,fg=#727169] ~ "

setw -g window-status-separator ""
setw -g window-status-format "#[fg=#727169] #I #W "
setw -g window-status-current-format "#[fg=#FFA066,bold] #I #W "
setw -g window-status-activity-style "fg=#E6C384"

set -g status-right-length 40
set -g status-right "#[fg=#C8C093]%Y-%m-%d #[fg=#C8C093]/ #[fg=#C8C093]%H:%M "

set -g pane-border-style "fg=#363646"
set -g pane-active-border-style "fg=#FFA066"

set -g message-style "bg=default,fg=#FFA066"
set -g message-command-style "bg=default,fg=#C8C093"

set -g mode-style "noattr,bg=#FFFFFF,fg=#000000"
set -g copy-mode-selection-style "bg=#FFFFFF,fg=#000000"

setw -g monitor-activity on
set -g visual-activity off
set -g visual-bell off
